-- 코드를 입력하세요
SELECT 
    T.USER_ID,
    T.PRODUCT_ID
FROM (
SELECT 
    USER_ID,
    PRODUCT_ID,
    COUNT(*) AS COUNT
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
) T
WHERE T.COUNT>=2
ORDER BY 1, 2 DESC