-- 코드를 입력하세요
SELECT 
    T.CAR_ID,
    ROUND(T.AVERAGE_DURATION,1)
FROM (
    SELECT 
        CAR_ID,
        AVG(DATEDIFF(END_DATE,START_DATE))+1 AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    GROUP BY CAR_ID
) T
WHERE T.AVERAGE_DURATION >= 7
ORDER BY 2 DESC, CAR_ID DESC 