-- 코드를 작성해주세요
SELECT 
    T.ROUTE,
    CONCAT(ROUND(T.TOTAL_DISTANCE,1),"km") AS TOTAL_DISTANCE,
    CONCAT(ROUND(T.AVERAGE_DISTANCE,2),"km") AS AVERAGE_DISTANCE
FROM (
SELECT 
    ROUTE,
    SUM(D_BETWEEN_DIST) AS TOTAL_DISTANCE,
    AVG(D_BETWEEN_DIST) AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE 
GROUP BY ROUTE
) T
ORDER BY T.TOTAL_DISTANCE DESC