-- 코드를 작성해주세요
SELECT 
    IF(MONTH(DIFFERENTIATION_DATE) IN (1,2,3), '1Q',
       IF(MONTH(DIFFERENTIATION_DATE) IN (4,5,6), '2Q',
          IF(MONTH(DIFFERENTIATION_DATE) IN (7,8,9), '3Q', '4Q') 
        )
      ) AS QUARTER,
    COUNT(*)
FROM ECOLI_DATA 
GROUP BY QUARTER
ORDER BY QUARTER