-- 코드를 작성해주세요
SELECT
    I1.ITEM_ID,
    I1.ITEM_NAME,
    I1.RARITY
FROM ITEM_INFO I1
JOIN ITEM_TREE T ON I1.ITEM_ID=T.ITEM_ID
JOIN ITEM_INFO I2 ON T.PARENT_ITEM_ID = I2.ITEM_ID
WHERE I2.RARITY = 'RARE'
ORDER BY 1 DESC