-- 코드를 작성해주세요
SELECT 
    T1.ID,
    T1.GENOTYPE,
    T2.GENOTYPE
FROM ECOLI_DATA T1
JOIN (
    SELECT 
        ID, 
        PARENT_ID,
        SIZE_OF_COLONY,
        DIFFERENTIATION_DATE,
        GENOTYPE
    FROM ECOLI_DATA 
) T2 ON T1.PARENT_ID = T2.ID
WHERE (T1.GENOTYPE & T2.GENOTYPE) = T2.GENOTYPE
ORDER BY 1