-- 코드를 작성해주세요
SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (M.MAX_SIZE - E.SIZE_OF_COLONY),
    ID
FROM ECOLI_DATA E
JOIN
(SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE,
    YEAR(DIFFERENTIATION_DATE) AS YEAR
 FROM ECOLI_DATA
 GROUP BY YEAR(DIFFERENTIATION_DATE)
) M ON YEAR(DIFFERENTIATION_DATE) = M.YEAR
ORDER BY 1, 2
    
    