-- 코드를 작성해주세요
SELECT 
    G.TOTAL_SCORE AS SCORE,
    G.EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM (
    SELECT H.EMP_NO, SUM(SCORE) TOTAL_SCORE 
    FROM HR_GRADE H
    GROUP BY EMP_NO
) G
JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
ORDER BY G.TOTAL_SCORE DESC
LIMIT 1
