-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, G.REPLY_ID, G.WRITER_ID, G.CONTENTS, G.CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY G ON B.BOARD_ID = G.BOARD_ID
WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
ORDER BY G.CREATED_DATE, B.TITLE 